version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "jmvbambico"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "jmvbambico"
    commit-message:
      prefix: "deps(dashboard)"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "jmvbambico"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
